export const GET_RECIPE_SUCCESS = "GET_RECIPE_SUCCESS";
export const GET_RECIPE_FAILURE = "GET_RECIPE_FAILURE";

export const UPDATE_RECIPE_REQUEST = "UPDATE_RECIPE_REQUEST";
export const UPDATE_RECIPE_SUCCESS = "UPDATE_RECIPE_SUCCESS";
export const UPDATE_RECUPE_FAILURE = "UPDATE_RECIPE_FAILURE";
