export const GET_MEALS = "GET_MEALS";
export const GET_SIDES = "GET_SIDES";

export const TITLE_CHANGE = "TITLE_CHANGE";
export const URL_CHANGE = "URL_CHANGE";
export const COMMENT_CHANGE = "COMMENT_CHANGE";
export const TAGS_CHANGE = "TAGS_CHANGE";
export const TAG_CHANGE = "TAG_CHANGE";
export const TYPE_CHANGE = "TYPE_CHANGE";
export const ADD_RECIPE_INITIAL = "ADD_RECIPE_INITIAL";

//Signup and Signin
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_EMAIL_CHANGED = "SIGN_IN_EMAIL_CHANGED";
export const SIGN_IN_PASSWORD_CHANGED = "SIGN_IN_PASSWORD_CHANGED";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
export const SIGN_UP_EMAIL_CHANGED = "SIGN_UP_EMAIL_CHANGED";
export const SIGN_UP_PASSWORD_CHANGED = "SIGN_UP_PASSWORD_CHANGED";
export const SIGN_UP_PASSWORD_CONFIRM_CHANGED =
  "SIGN_UP_PASSWORD_CONFIRM_CHANGED";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";
export const FORGOT_PASSWORD_EMAIL_CHANGED = "FORGOT_PASSWORD_EMAIL_CHANGED";

//Signin

//Status
export const GET_TOKEN = "GET_TOKEN";
export const REMOVE_TOKEN = "REMOVE_TOKEN";

export const UPDATE_RECIPE = "UPDATE_RECIPE";
